services:
  pokemon-go-stats-tracker:
    image: ghcr.io/matthiasharzer/go-stats-tracker:latest
    container_name: pokemon-go-stats-tracker
    restart: unless-stopped
    ports:
      - "4000:4000"
    command: run -p 4000 -d /app/data/db.sqlite3
    environment:
      REDIRECT_URL: ${REDIRECT_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      APP_ID: ${APP_ID}
      PICKER_API_KEY: ${PICKER_API_KEY}
    volumes:
      - ./data:/app/data
